# Generated by Django 4.0.2 on 2022-02-21 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_usercar_story'),
        ('account', '0005_alter_customuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='garage',
            field=models.ManyToManyField(related_name='profile_owner', to='car.UserCar', verbose_name='Profile owner'),
        ),
        migrations.CreateModel(
            name='CommercialUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_address', models.CharField(max_length=255, verbose_name='legal address')),
                ('employees', models.ManyToManyField(related_name='commercial_employees', to=settings.AUTH_USER_MODEL, verbose_name='staff')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_page_owner', to=settings.AUTH_USER_MODEL, verbose_name='Commercial page owner')),
                ('service_list', models.ManyToManyField(to='car.Maintenance')),
                ('serviced_car', models.ManyToManyField(related_name='serviced_car', to='car.UserCar', verbose_name='List of serviced car')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='serviced_by',
            field=models.ManyToManyField(default=None, related_name='serviced_by', to='account.CommercialUser', verbose_name='Service used'),
        ),
    ]
