# Generated by Django 4.0.2 on 2022-02-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_garage_commercialuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialuser',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Legal name'),
        ),
        migrations.AddField(
            model_name='commercialuser',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo/%Y/%m/%d', verbose_name='Logo image'),
        ),
    ]
