# Generated by Django 4.0.2 on 2022-02-22 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_usercar_mileage'),
        ('account', '0009_alter_customuser_garage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialuser',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='commercial_employees', to=settings.AUTH_USER_MODEL, verbose_name='staff'),
        ),
        migrations.AlterField(
            model_name='commercialuser',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercial_page_owner', to=settings.AUTH_USER_MODEL, verbose_name='Commercial page owner'),
        ),
        migrations.AlterField(
            model_name='commercialuser',
            name='serviced_car',
            field=models.ManyToManyField(blank=True, related_name='serviced_car', to='car.UserCar', verbose_name='List of serviced car'),
        ),
    ]
